#!/usr/bin/env bash
## by default, usermode references ~/.TinyTeX
if [ ! -d ~/.TinyTeX/texmf-home/web2c ]; then
  tlmgr init-usertree
  if [ ! -d ~/.TinyTeX/texmf-home/web2c ]; then
    echo "ERROR: tlmgr init-usertree did not create ~/.TinyTeX/texmf-home/web2c" 1>&2
    exit 1
  fi
fi
tlmgr update --self
tlmgr install --usermode microtype
tlmgr install --usermode euler
tlmgr install --usermode merriweather
tlmgr install --usermode fontaxes
tlmgr install --usermode mweights
tlmgr install --usermode mathastext
tlmgr install --usermode relsize
# Searching here led me to 'ms': https://www.ctan.org/pkg/ragged2e
tlmgr install --usermode ms
tlmgr install --usermode xcolor
tlmgr install --usermode colortbl
tlmgr install --usermode xpatch
tlmgr install --usermode environ
tlmgr install --usermode trimspaces
tlmgr install --usermode lastpage
tlmgr install --usermode textpos
tlmgr install --usermode mdframed
tlmgr install --usermode needspace
tlmgr install --usermode titlesec
# Searching here led me to 'koma-script': https://www.ctan.org/pkg/scrextend
tlmgr install --usermode koma-script
# Searching here led me to 'preprint': https://www.ctan.org/pkg/authblk
tlmgr install --usermode preprint
tlmgr install --usermode footmisc
tlmgr install --usermode fancyhdr
tlmgr install --usermode abstract
tlmgr install --usermode enumitem
tlmgr install --usermode quoting
# Searching here led me to 'sttools': https://www.ctan.org/pkg/stfloats
tlmgr install --usermode sttools
tlmgr install --usermode forarray
tlmgr install --usermode xstring
tlmgr install --usermode siunitx
#ref: https://github.com/xdanaux/moderncv/issues/34#issuecomment-266212880
#ref: https://wiki.archlinux.org/index.php/TeX_Live_FAQ#Q:_pdftex_and.2For_dvips_uses_bitmap_fonts_instead_of_type1_postscript_fonts
updmap -user
exit 0
