---
title: "Example of journal's templates"
resource_files:
  - resources
---

# List of templates

```{r, setup, include = FALSE}
library(rticles)
```

```{r, child = "_child_examples.Rmd"}
```

```{r, include = FALSE}
# We generate the YAML file on the fly to render the gallery

# list of sites
articles <- lapply(journals(), function(journal) {
  name <- yaml::read_yaml(rticles:::pkg_file_template(journal, "template.yaml"))$name
  img = file.path("resources", paste0(journal, "_article.gif"))
  href = file.path("resources", paste0(journal, "_article.pdf"))
  repo_url = "https://github.com/rstudio/rticles/tree/master/inst/rmarkdown/templates/"
  if (!file.exists(img) || !file.exists(href)) return(list())
  list(
    title = sprintf("%s - %s", journal, name),
    fun = sprintf("%s_article", journal),
    img = img, 
    href = href,
    source = paste0(repo_url, journal)
  )
})

articles <- Filter(length, articles)
```

The examples below illustrate all the article's template included into this package.

```{r}
library(htmltools)
thumbs <- function(ncol = 2, title, href, img, source, fun) {
  div(class = sprintf("col-sm-%s", 12/ncol), 
      h2(title),
      pre(class = c("sourceCode", "yaml"), 
                    code(class = c("sourceCode", "yaml"), 
                         sprintf("output: %s", fun))),
      a(class = "thumbnail", 
        title = title, href = href, img(src = img)),
      a(class = "source-repo", href = source, "Source of template")
  )
}
```

```{r, eval = FALSE}
quillt::thumbnails(lapply(articles, function(x) {
    thumbs(title = x$title, img = x$img, 
           href = x$href, ncol = 2, source = x$source, 
           fun = x$fun)
  }), ncol = 2)
```

```{r}
str(lapply(articles, function(x) {
    thumbs(title = x$title, img = x$img, 
           href = x$href, ncol = 2, source = x$source, 
           fun = x$fun)}))
```


